schema: schema.docs.graphql
documents: src/**/*.graphql
extensions:
  codegen:
    overwrite: true
    generates:
      src/generated.ts:
        plugins:
          - "typescript"
          - "typescript-operations"
          - "typed-document-node"
